// File generated by FlutterFire CLI.
// PLease do not edit this file manually.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQjoV8hVq0oVG2XlWXr-mBiyEdgFGaNjA',
    appId: '1:599296548737:web:77ca4e3dce42fd4eb65280',
    messagingSenderId: '599296548737',
    projectId: 'buspoint-49ea0',
    authDomain: 'buspoint-49ea0.firebaseapp.com',
    storageBucket: 'buspoint-49ea0.appspot.com',
    measurementId: 'G-12VZJLH13F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdOY8rXDYeRn0Zp5gx2LWWOTpsahfC3RM',
    appId: '1:599296548737:android:ca68c23ed70087d1b65280',
    messagingSenderId: '599296548737',
    projectId: 'buspoint-49ea0',
    storageBucket: 'buspoint-49ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD9pnwXdx8doFnvgFcvFUWS4uCzTVzvKw',
    appId: '1:599296548737:ios:fb6139ca28f73238b65280',
    messagingSenderId: '599296548737',
    projectId: 'buspoint-49ea0',
    storageBucket: 'buspoint-49ea0.appspot.com',
    androidClientId: '599296548737-jj01qjanje7f3g67icn5vhu538s743k1.apps.googleusercontent.com',
    iosClientId: '599296548737-6fdust2lfmcla5usf5e4jqlggasm6pf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD9pnwXdx8doFnvgFcvFUWS4uCzTVzvKw',
    appId: '1:599296548737:ios:fb6139ca28f73238b65280',
    messagingSenderId: '599296548737',
    projectId: 'buspoint-49ea0',
    storageBucket: 'buspoint-49ea0.appspot.com',
    androidClientId: '599296548737-jj01qjanje7f3g67icn5vhu538s743k1.apps.googleusercontent.com',
    iosClientId: '599296548737-6fdust2lfmcla5usf5e4jqlggasm6pf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQjoV8hVq0oVG2XlWXr-mBiyEdgFGaNjA',
    appId: '1:599296548737:web:8207e72cede77131b65280',
    messagingSenderId: '599296548737',
    projectId: 'buspoint-49ea0',
    authDomain: 'buspoint-49ea0.firebaseapp.com',
    storageBucket: 'buspoint-49ea0.appspot.com',
    measurementId: 'G-BT1Z473SZG',
  );
}
